### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by srekkas** [hat-open/hat-syslog#3]
Hi,

  I try to run hat-syslog on docker. Container starts, but throws error. How config handler or what needed?

```
version: '3.8'

services:
  hat-syslog:
    image: bozokopic/hat-syslog
    container_name: hat-syslog
    ports:
      - "6514:6514/tcp"
      - "6514:6514/udp"
      - "23020:23020"
    volumes:
      - ./data:/hat-syslog"
```

```
[2024-03-27 13:28:01,354 ERROR hat.syslog.server.syslog] udp client error: 'NoneType' object has no attribute 'groupdict'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hat/syslog/server/syslog.py", line 159, in _receive_loop
    msg = encoder.msg_from_str(msg_bytes.decode())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hat/syslog/encoder.py", line 28, in msg_from_str
    match = _msg_pattern.fullmatch(msg_str).groupdict()

```

**Comment by bozokopic** [comment]
it appears that syslog server received udp message which is not valid RFC 5424 syslog message.

at this time, hat-syslog supports only messages formatted in accordance to this specification
(https://www.rfc-editor.org/rfc/rfc5424#section-6).

if your client has this option, i would advise usage of latest syslog standard formating
